pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=Formatting check
      - check-success=PR Windows
    actions:
      merge:
        method: squash
        commit_message: default
